export const streetsByDistrict: Record<string, string[]> = {
  kentron: [
    "Abovyan St",
    "Agh Aram St",
    "Amiryan St",
    "Aram St",
    "Arami St",
    "Arshakunyats Ave",
    "Azatutyan Ave",
    "Baghramyan Ave",
    "Buzand St",
    "Charents St",
    "Dro St",
    "France Square",
    "Gevorgyan St",
    "Grigor Lusavorich St",
    "Hanrapetutyan St",
    "Isahakyan St",
    "Khanjyan St",
    "Koryun St",
    "Mashtots Ave",
    "Martiros Saryan St",
    "Moscovyan St",
    "Nalbandyan St",
    "Nzhdeh St",
    "Parpetsi St",
    "Paronyan St",
    "Pushkin St",
    "Republic Square",
    "Sayat-Nova Ave",
    "Spandarian St",
    "Terian St",
    "Tigran Mets Ave",
    "Tigranyan St",
    "Tumanyan St",
    "Vardanants St",
    "Vazgen Sargsyan St",
  ],

  arabkir: [
    "Andranik St",
    "Antarayin St",
    "Ashtarak Highway",
    "Azatutyan Ave",
    "Baghramyan Ave",
    "Byuzandakan St",
    "Davit Anhaght St",
    "Dzoraghbyur St",
    "Hakob Hakobyan St",
    "Kaghakatsin St",
    "Kievyan St",
    "Komitas Ave",
    "Manandyan St",
    "Margaryan St",
    "Mher Mkrtchyan St",
    "Muratsan St",
    "Norageryan St",
    "Paruyr Sevak St",
    "Tbilisi Highway",
    "Tigranyan St",
    "Vardanants St",
  ],

  davtashen: [
    "Davtashen 1st District",
    "Davtashen 2nd District",
    "Davtashen 3rd District",
    "Davtashen 4th District",
    "Gegham St",
    "Gyumrian Highway",
    "Hovhannes Shiraz St",
    "Movses Khorenatsi St",
    "Tsitsernakaberd Highway",
    "Vahan Teryan St",
  ],

  ajapnyak: [
    "Ajapnyak 1st District",
    "Ajapnyak 2nd District",
    "Ajapnyak 3rd District",
    "Alek Manukyan St",
    "Antarayin St",
    "Argishti St",
    "Artsvik St",
    "Ashotavan St",
    "Garegin Nzhdeh St",
    "Gyumrian Highway",
    "Hrachya Kochar St",
    "Hovhannes Shiraz St",
    "Khachatur Abovyan St",
    "Leningradsyan St",
    "Paruyr Sevak St",
    "Vahan Teryan St",
    "Vardavar St",
  ],

  shengavit: [
    "Arshakunyats Ave",
    "Artashat Highway",
    "David Bek St",
    "Garegin Nzhdeh Square",
    "Kamo St",
    "Karmir Blur St",
    "Raffi St",
    "Rubinyants St",
    "Sebastia St",
    "Shengavit 1st District",
    "Shengavit 2nd District",
    "Shengavit 3rd District",
    "Shengavit 4th District",
    "Tigranashen St",
    "Vardges Sureniants St",
    "Yerznkyan St",
  ],

  kanakerZeytun: [
    "Arshakunyats Ave",
    "Avan-Arinj Highway",
    "Charentsavan St",
    "Gyulbenkyan St",
    "Kanaker 1st District",
    "Kanaker 2nd District",
    "Movses Khorenatsi St",
    "Paronyan St",
    "Tigranashen St",
    "Vazgen Sargsyan St",
    "Yervand Kochar St",
    "Zeytun 1st District",
    "Zeytun 2nd District",
    "Zeytun 3rd District",
  ],

  norNork: [
    "Antarayin St",
    "Arshakunyats Ave",
    "Gyumrian Highway",
    "Halabyan St",
    "Margaryan St",
    "Nor Nork 1st District",
    "Nor Nork 2nd District",
    "Nor Nork 3rd District",
    "Nor Nork 4th District",
    "Nor Nork 5th District",
    "Sebastia St",
    "Teryan St",
  ],

  malatiaSebastia: [
    "Ararat St",
    "Armenakyan St",
    "Khachatur Abovyan St",
    "Malatia 1st District",
    "Malatia 2nd District",
    "Malatia 3rd District",
    "Malatia 4th District",
    "Mushakan St",
    "Sebastia St",
    "Tigranyan St",
    "Zvartnots Highway",
  ],

  avan: [
    "Abovyan Highway",
    "Avan 1st District",
    "Avan 2nd District",
    "Avan 3rd District",
    "Avan Ave",
    "Avan-Arinj Highway",
    "Geghadir St",
    "Haghpat St",
    "Nor Arinj St",
    "Tsaghkadzori Highway",
  ],

  erebuni: [
    "Artashat Highway",
    "David Bek St",
    "Erebuni 1st District",
    "Erebuni 2nd District",
    "Erebuni 3rd District",
    "Karmir Blur St",
    "Khanjyan St",
    "Nairi Zarian St",
    "Sepuh St",
    "Tigranashen St",
    "Zvartnots Airport Area",
  ],

  norkMarash: [
    "Antarayin St",
    "Marash St",
    "Mher Mkrtchyan St",
    "Nork 1st District",
    "Nork 2nd District",
    "Nork 3rd District",
    "Nork Massiv",
    "Tsaghkadzori Highway",
    "Yeritsyan St",
  ],

  nubarashen: [
    "Artashat Highway",
    "Nubarashen 1st District",
    "Nubarashen 2nd District",
    "Nubarashen 3rd District",
    "Nubarashen 4th District",
  ],

  other: [],
};
