/**
 * AUTO-GENERATED from OpenStreetMap via Overpass API.
 * Generated: 2026-09-03T13:35:22.631Z — Total: 1418 streets
 * Regenerate: node scripts/fetch-yerevan-streets.mjs
 */

export const streetsByDistrict: Record<string, string[]> = {
  kentron: [
    "1915 Battle of Van street",
    "Abovyan street",
    "Adana street",
    "Admiral Isakov Avenue",
    "Agatangeghos street",
    "Agatangeghos Street",
    "Aghayan street",
    "Aghyusagorcner street",
    "Alek Manoukyan street",
    "Alek Manukyan street",
    "Aleksandr Spendiarian street",
    "Alexandr Harutyunyan street",
    "Amerikyan street",
    "Amiryan Street",
    "Antarayin street",
    "Anton Kochinyan street",
    "Aram street",
    "Aram street lane",
    "Architects street",
    "Argishti street",
    "Armen Takhtajyan street",
    "Armenak Armenakyan Street",
    "Arshakuniats Avenue",
    "Arshakuniats Avenue 1st Lane",
    "Arshakuniats Avenue 2nd lane",
    "Atenk street",
    "Avag Petrosyan street",
    "Avetik Isahakyan street",
    "Ayas street",
    "Aygedzor street",
    "Aygedzor street 1st lane",
    "Aygestan 9th street",
    "Azatutyan Avenue",
    "Bardzraberd street",
    "Beirut street",
    "Brazil Square",
    "Bryusov Street",
    "Budapesht Street",
    "Burnazyan street",
    "Buzand street",
    "Charents street",
    "Charents street 1st lane",
    "Charents street 2nd lane",
    "Charents street 3rd lane",
    "Charles Aznavour Square",
    "Deghatan street",
    "Derenik Demirchyan street",
    "Dzoragyugh street",
    "Dzorapi Street",
    "Edgar Hovhannisyan street",
    "Eduard Mirzoyan Street",
    "Europe Square",
    "Ferdowsi street",
    "Fizkulturnikner street",
    "Frik Street",
    "Galoyan Yeghbayrner street",
    "Getari street",
    "Gevorg Emin street",
    "Gevorg Jahukyan street",
    "Gevorg Qochar street",
    "Glinka street",
    "Glinka Street",
    "Gohar Gasparyan street",
    "Gr. Harutyunyan street",
    "Grigor Chubaryan street",
    "Grigor Lusavorich street",
    "Hakob Paronyan street",
    "Hanrapetutyan Street",
    "Hanrapetutyan street 2nd lane",
    "Hin Erevantsu Street",
    "Hin Yerevantsi street",
    "Hovhannes Kozerni street",
    "Hrant Shahinyan street",
    "Hrazdan riverbank road",
    "India Street",
    "Isaac Alikhanian street",
    "Isaac Alikhanian street deadlock",
    "Israelyan street",
    "Israyelyan street",
    "Italy street",
    "Kajaznuni street",
    "Karen Demirchyan street",
    "Kashegortsner street",
    "Khanjyan street",
    "Khoren Abrahamyan street",
    "Khorenatsi street 3rd deadlock",
    "Khorhrdaran street",
    "King Pap Street",
    "Kond",
    "Kond 1st street",
    "Kond street",
    "Konstantin Orbelyan Street",
    "Kor street",
    "Koryun street",
    "Koryun street 1st lane",
    "Koryun street deadlock",
    "Kristapor street",
    "Kristapor street 1st lane",
    "Kristapor street 2nd lane",
    "Kristapor street 3rd lane",
    "Lalayants street",
    "Lambron street",
    "Leo street",
    "Leonid Azgaldyan street",
    "Ler Kamsari Street",
    "Lusinyants street",
    "Manuk Abeghyan street",
    "Marshal Baghramyan Avenue",
    "Melik-Adamyan Street",
    "Mher Mkrtchyan street",
    "Mikael Chailakhyan street",
    "Mkhitar Heratsi Street",
    "Moskovyan street",
    "Movses Khorenatsi street",
    "Movses Khorenatsi street 1st deadlock",
    "Movses Khorenatsi street 1st lane",
    "Movses Khorenatsi street 2nd lane",
    "Movses Khorenatsi street 3rd deadlock",
    "Movses Khorenatsi street 4th lane",
    "Myasnikyan avenue",
    "Nalbandyan street",
    "Nalbandyan street lane",
    "Nar-Dos street",
    "Nar-Dos Street",
    "Nar-Dos street 1st lane",
    "New Highway",
    "Nikita Simonyan street",
    "Noragyugh street",
    "Northern Avenue",
    "Ostrovski street",
    "Paronyan street 3rd lane",
    "Parpetsi lane",
    "Parpetsi Street",
    "Pavstos Buzand street",
    "Prague street",
    "Proshyan street",
    "Proshyan street 1st lane",
    "Pushkin Street",
    "Raphael Lemkin street",
    "Republic Square",
    "Rostom street",
    "Rustaveli street",
    "Sakharov square",
    "Sakharov street",
    "Saralanj highway",
    "Saralanj Highway",
    "Saralanji street",
    "Saralanji Street",
    "Sari Tagh 5th and 6th lines",
    "Sarmen street",
    "Saryan Street",
    "Sayat Nova avenue",
    "Sayat Nova deadstreet",
    "Sayat-Nova Avenue",
    "Sayat-Nova avenue deadlock",
    "Sergey Mergelyan street",
    "Sevan street",
    "Shara Talian street",
    "Sharimanyan street",
    "Silva Kaputikyan street",
    "Simeon Yerevantsi street",
    "Simon Vratsyan street",
    "Sisvan street",
    "Square of France",
    "Stepan Zoryan street",
    "Surb Hovhannes street",
    "Tadevos Avdalbegyan street",
    "Tairov street",
    "Tamanyan street",
    "Tchaykovsky street",
    "Ter-Grigorian street",
    "Teryan street",
    "Tigran Mets avenue",
    "Tigran Mets Avenue 1st deadlock",
    "Tigran Mets avenue 1st lane",
    "Tigran Mets avenue 3rd lane",
    "Tolstoy street",
    "Tpagrichner street",
    "Tsaturyan street",
    "Tsitsernakaberd Highway",
    "Tskhakhotagortsneri street",
    "Tumanyan 2nd Pass",
    "Tumanyan street",
    "Uruguay square",
    "Vardanants deadlock",
    "Vardanants Street",
    "Vardanants street 2nd lane",
    "Vazgen Sargsyan street",
    "Verfel street",
    "Verin Antarayin street",
    "Victory Bridge",
    "Voskerichnery street",
    "Yekmalyan street",
    "Yervand Kochar street",
    "Yeznik Koghbatsi street",
    "Zakian street",
    "Zarobyan street",
    "Zavaryan street",
    "Улица Хорен Абраамян",
    "Բարձրաբերդի փողոց",
    "Նորագյուղ փողոց",
  ],

  arabkir: [
    "Aghbyur Serob Street",
    "Alexey Hekimyan street",
    "Alexey Yekimyan street",
    "Anna Ter-Avetikyan street",
    "Aram Khachatryan street",
    "Aram Khachatryan street 1st lane",
    "Armenuhi Tigranyan street",
    "Avet Avetisyan Street",
    "Avetis Aharonyan Street",
    "Aygedzor street",
    "Aygedzor street 1st lane",
    "Aygektci street",
    "Aygektci Street",
    "Azatutyan Avenue",
    "Babayan street",
    "Barbyus street",
    "Barbyus Street",
    "Budaghyan street",
    "Davit Hovhannes street",
    "Davtashen bridge",
    "Elen Byuzand street",
    "Gevorg Vardanyan street",
    "Ghapantsian street",
    "Griboyedov street",
    "Griboyedov street 4th lane",
    "Grigor Artsrunu street",
    "Gulakyan street",
    "Gulakyan Street",
    "Gyulbenkyan street",
    "Gyulbenkyan street 1st lane",
    "Hakob Hakobyan street",
    "Hakob Hakobyan Street",
    "Hakob Hakobyan street lane",
    "Hamo Sahyan street",
    "Hayrik Muradyan street",
    "Henrik Malyan street",
    "Hovsep Arghutian street",
    "Hovsep Arghutian street 1st deadlock",
    "Hovsep Arghutian street 1st lane",
    "Hovsep Emin street",
    "Hovsep Emin street 1st lane",
    "Hrachya Kochar street",
    "Hrachya Kochar Street",
    "Hrachya Kochar street 1st Lane",
    "Hrachya Kochar street 2nd lane",
    "Hrachya Tamranzyan street",
    "Hrazdan Gorge street",
    "Hrazdan riverbank road",
    "Hrazdan Riverbank Road",
    "James Bryce street",
    "Kalents street",
    "Kanaker children's city street",
    "Karp Khachvankyan street",
    "Khnko Aper street",
    "Kievyan bridge",
    "Kievyan street",
    "Kievyan street 1st lane",
    "Kievyan street 2nd lane",
    "Komitas avenue",
    "Komitas Avenue 1st lane",
    "Lambada bridge",
    "Ler Kamsari street",
    "Ler Kamsari Street",
    "Levon Khechoyan street",
    "Malkhasyants lane",
    "Malkhasyants street",
    "Mamikonyants street",
    "Mamikonyants street 1st lane",
    "Manushyan street",
    "Manushyan Street",
    "Maria Jacobsen street",
    "Maro Margaryan street",
    "Marshal Baghramyan Avenue",
    "Marshal Baghramyan avenue 2nd lane",
    "Marshal Baghramyan street 3rd lane",
    "Nairi Zaryan street",
    "Nairi Zaryan street 1st lane",
    "Nikogajos Tigranyan deadlock",
    "Nikogajos Tigranyan street",
    "Nikoghayos Adonts Street",
    "Nikoghayos Tigranyan street",
    "Nikol Duman street",
    "Nikol Duman Street",
    "Northern Ray",
    "Orbeli Brothers street",
    "Orbeli Brothers Street",
    "Paruyr Sevak street",
    "Proshyan street",
    "Qanaqer 1st street",
    "Qeri street",
    "Qeri street deadlock",
    "Riga street",
    "Riga street deadlock",
    "Ruben Sevak street",
    "Saralanj Highway",
    "Sepuh street",
    "Sevastopolian street",
    "Sevkaretsi Sako street",
    "Shahsuvaryan street",
    "Shirvanzade street",
    "Shrdjancik Tunnel Street",
    "Slavik Chiloyan street",
    "Sos Sargsyan street",
    "Sose street",
    "Sose street 1st lane",
    "Sose street 2nd lane",
    "St. Abgar street",
    "Sundukian street",
    "Sundukyan Street",
    "Svetlana Grigoryan street",
    "Tavrizyan street",
    "Tbilisian Highway",
    "Tbilisian Highway lane",
    "Tolbukhin street",
    "Vagharsh Vagharshyan street",
    "Vagharsh Vagharshyan Street",
    "Vagharsh Vagharshyan street lane",
    "Vahagn Davtian Street",
    "Vahagn Davtian street 1st lane",
    "Vahagn Davtian street 2nd lane",
    "Vahagn Davtyan street",
    "Vahagn Davtyan Street",
    "Vahram Papazian street 2nd lane",
    "Vahram Papazyan street",
    "Vazgen I street",
    "Victor Hambardzumyan street",
    "Vratsakan street",
    "Vratsakan street 2nd lane",
    "Vratsakan street 4th lane",
    "Yerevan-Kanakeravan highway",
    "Yerznkian street",
    "Yerznkian Street",
    "Zakaria Sarkavag Street",
    "Zhirayr Ananyan street",
    "Շրջանցիկ թունել, Կորեայի ձոր",
  ],

  avan: [
    "Almati street",
    "Artashes Shahinyan street",
    "Artashes Shahinyan street 1st lane",
    "Artashes Shahinyan street 2nd lane",
    "Artashes Shahinyan street 3rd lane",
    "Artashes Shahinyan street 4th lane",
    "Askhabad street",
    "Avan 10th street",
    "Avan 12th street",
    "Avan 3rd street",
    "Avan 4th street",
    "Avan 4th street 1st lane",
    "Avan 4th street 2nd lane",
    "Avan 4th street 3rd lane",
    "Avan 4th street 4th lane",
    "Avan 5th street",
    "Avan 5th street 1st lane",
    "Avan 6th street",
    "Avan 6th street 1st lane",
    "Avan 6th street 2nd lane",
    "Avan 8th street",
    "Avan-Arinj 1st micro",
    "Avan-Arinj 1st microdistrict",
    "Avan-Arinj 2nd microdistrict",
    "Bagrevand 41st street",
    "Bagrevand 50th street",
    "Bagrevand 51st street",
    "Bryusov taghamas",
    "Charenc taghamas",
    "Davit Malyan street",
    "Duryan street",
    "Gai avenue",
    "General Safaryan street",
    "Hovhannisyan taghamas",
    "Hrachya Acharyan street 1st lane",
    "Hrachya Acharyan Street 1st lane",
    "Hrachya Acharyan street 2nd lane",
    "Isahakyan taghamas",
    "Khachatur Abovyan district 2nd street",
    "Khachatur Abovyan district 2nd street 1st deadlock",
    "Malyan lane",
    "Marshal Babajanyan street",
    "Marshal Babajanyan street lane",
    "Marshal Khudyakov street",
    "Marshal Khudyakov street 1st lane",
    "Marshal Khudyakov street 2nd lane",
    "Marshal Khudyakov street 3rd lane",
    "Marshal Khudyakov street 4th lane",
    "Marshal Khudyakov street 5th lane",
    "Mesrop Mashtots street",
    "Narekatsi block",
    "Petros Duryan district 12th street",
    "Petros Duryan district 14th street",
    "Petros Duryan district 15th street",
    "Petros Duryan district 1st street 1st lane",
    "Quchak block",
    "Rubiniants street",
    "Rubiniants street lane",
    "Sayat-Nova disrtict",
    "Tamruchi street",
    "Tashkend street",
    "Tashkend street lane",
    "Tbilisian Highway",
    "Tsarav Aghbyur street",
    "Tsarav Aghbyuri Street",
    "Tumanyan taghamas",
    "Vahan Teryan district 1st street",
    "Vakhtangov street",
    "Varouzhan block",
  ],

  davtashen: [
    "Aghababyan street",
    "Anastas Mikoyan street",
    "Andranik Iosifyan street",
    "Ashtarak highway",
    "Davidashen 10th street",
    "Davidashen 1st street",
    "Davidashen 4th street",
    "Davidashen 5th street",
    "Davidashen 6th street",
    "Davidashen 7th street",
    "Davidashen 8th street",
    "Davidashen 9th street",
    "Davtashen 1st street 1st lane",
    "Davtashen 1st street 2nd lane",
    "Davtashen bridge",
    "Dzor 1",
    "Dzor 2 district",
    "Halabyan Street",
    "Hrazdan Riverbank Road",
    "Huysi Avan District 1st street",
    "Huysi Avan District 3rd street",
    "Huysi Avan District 4th street",
    "Huysi Avan District 5th street",
    "Melkumov street",
    "Mush 2nd street",
    "Paris Herouni street",
    "Pirumyanner",
    "Pirumyanner street",
    "Samvel Gevorqyan street",
    "Sasna Tsrer street",
    "SasnaTsrer street",
    "Tigran Petrosyan street",
    "Yeghvard highway",
    "Գևորգ Չաուշ",
    "Դավթաշեն 10-րդ փողոց",
    "Դավթաշենի 5-րդ փողոց",
    "Դավթաշենի 7-րդ փողոց",
  ],

  erebuni: [
    "Aivazovski street",
    "Argishti District",
    "Arin Berd streeet 4th lane",
    "Arin Berd street",
    "Arin Berd street 3rd lane",
    "Arin Berd street 5th lane",
    "Artashat-Sevan highway",
    "Artsakh avenu",
    "Artsakh avenue",
    "Artsakh Avenue",
    "Artsakh Avenue 2nd lane",
    "Artsakh avenue 4th lane",
    "Atoyan Street",
    "Atoyan street passing",
    "Avanesov street",
    "Avanesov street 1st lane",
    "Avanesov street 2nd lane",
    "Avanesov street deadlock",
    "Azatamartikner Avenue",
    "Azatamartikner Avenue 1st lane",
    "Azatamartikner Avenue 2nd lane",
    "Azatamartikner Avenue 3rd lane",
    "Azatamartikner Avenue 4th lane",
    "Azatamartikner Avenue 5th lane",
    "Azatamartikner lane",
    "Azatamartikner street",
    "Belinsky Street",
    "Burnazyan street",
    "Burnazyan street 1st lane",
    "Cherneshevski street",
    "Crystalglass way",
    "David Bek 1st street",
    "David Bek street lane",
    "Davit Bek street",
    "Erebuni Square",
    "Erebuni street",
    "Erkatgits street",
    "Erkatughayinner 2nd street",
    "Erkatughayinner 3rd street",
    "Erkatughayinner 4th street",
    "Erkatughayinner 5th street",
    "Erkatughayinner 6th street",
    "Erkatughayinner 7th street",
    "Erkatughayinner 8th street",
    "Erkatughayinner street",
    "Erkatughayinneri street",
    "Gajagortsner 1st street",
    "Gajagortsner 3rd street",
    "Gajagortsner street",
    "Gajegortsneri 2nd street",
    "Garegin Hovsepyan Street",
    "Garegin Nzhdeh Street",
    "Glinka street",
    "Glinka Street",
    "Glinka street lane",
    "Grigor and Sargis Gurzadyan street",
    "Gurgen Mahari street",
    "Jack Iv Kusto street",
    "Jrashen 1st street",
    "Jrashen 1st street 1st lane",
    "Jrashen 1st street 2nd lane",
    "Jrashen 2nd street",
    "Jrashen 3rd street",
    "Khachik Dashtenc street",
    "Khaghag Don street",
    "Khaghagh Don street",
    "Krilov street",
    "Kristapor street",
    "Lomonosov street",
    "Loris Melikov street",
    "Michurin Street",
    "Movses Khorenatsi street",
    "Muratsan street",
    "Muratsan Street",
    "Muratsan street 1st street",
    "Muratsan street 2nd lane",
    "Mushavan  3th street",
    "Mushavan 10th street",
    "Mushavan 11th street",
    "Mushavan 1st street",
    "Mushavan 2nd street",
    "Mushavan 2nd street 1st lane",
    "Mushavan 4th street",
    "Mushavan 5th street",
    "Mushavan 6th street",
    "Mushavan 7th street",
    "Mushavan 8th street",
    "Mushavan 9th street",
    "New Highway",
    "Nor Aresh 11th street",
    "Nor Aresh 11th street lane",
    "Nor Aresh 12th street",
    "Nor Aresh 14th street",
    "Nor Aresh 15th street",
    "Nor Aresh 16th street",
    "Nor Aresh 17th street",
    "Nor Aresh 19th street",
    "Nor Aresh 20th street",
    "Nor Aresh 20th street backtreet",
    "Nor Aresh 20th street lane",
    "Nor Aresh 22nd street",
    "Nor Aresh 24th street",
    "Nor Aresh 25th street",
    "Nor Aresh 27th street",
    "Nor Aresh 28th street",
    "Nor Aresh 29th street",
    "Nor Aresh 2nd street",
    "Nor Aresh 30th street",
    "Nor Aresh 31st street",
    "Nor Aresh 32nd street",
    "Nor Aresh 33rd street",
    "Nor Aresh 34th street",
    "Nor Aresh 34th street 1st lane",
    "Nor Aresh 34th street 2nd lane",
    "Nor Aresh 35th street",
    "Nor Aresh 36th street",
    "Nor Aresh 37th street",
    "Nor Aresh 37th street 1st lane",
    "Nor Aresh 38th street",
    "Nor Aresh 39th street",
    "Nor Aresh 3rd street",
    "Nor Aresh 40th street",
    "Nor Aresh 41st street",
    "Nor Aresh 41st street 1st lane",
    "Nor Aresh 42nd street",
    "Nor Aresh 43rd street",
    "Nor Aresh 44th street",
    "Nor Aresh 45th street",
    "Nor Aresh 46th street",
    "Nor Aresh 48th street",
    "Nor Aresh 4th street",
    "Nor Aresh 50th street",
    "Nor Aresh 50th street lane",
    "Nor Aresh 5th street",
    "Nor Aresh 7th street",
    "Nor Aresh 8th street",
    "Nor Aresh 9th street",
    "Nubarashen highway",
    "Nubarashen street",
    "Rostovyan street",
    "Sari Tag 10th line",
    "Sari Tag 11 street",
    "Sari Tag 22 street",
    "Sari Tag 25 street",
    "Sari Tag 28th street  1st lane",
    "Sari Tag 28th street  2nd lane",
    "Sari Tag 28th street 1st lane",
    "Sari Tag 3rd and 4th lines",
    "Sari Tag 5th and 6th lines",
    "Sari Tag 8-th backstreet",
    "Sari Tagh 10th line",
    "Sari Tagh 10th street",
    "Sari Tagh 11th street",
    "Sari Tagh 12th street",
    "Sari Tagh 13th lane",
    "Sari Tagh 13th street",
    "Sari Tagh 14th street",
    "Sari Tagh 15th street",
    "Sari Tagh 16th street",
    "Sari Tagh 17th street",
    "Sari Tagh 18th street",
    "Sari Tagh 19A street",
    "Sari Tagh 19th street",
    "Sari Tagh 1st and 2nd lines",
    "Sari Tagh 1st street",
    "Sari Tagh 20th street",
    "Sari Tagh 21 street",
    "Sari Tagh 21st street",
    "Sari Tagh 22nd street",
    "Sari Tagh 23rd street",
    "Sari Tagh 24th street",
    "Sari Tagh 26th street",
    "Sari Tagh 27th street",
    "Sari Tagh 28 street",
    "Sari Tagh 2nd street",
    "Sari Tagh 3rd and 4th lines",
    "Sari Tagh 3rd street",
    "Sari Tagh 4th street",
    "Sari Tagh 5th and 6th lines",
    "Sari Tagh 5th street",
    "Sari Tagh 5th Street",
    "Sari Tagh 6th street",
    "Sari Tagh 7 backsteet",
    "Sari Tagh 7th lane",
    "Sari Tagh 7th street",
    "Sari Tagh 8 and 9 lines",
    "Sari Tagh 8th and 9th lines",
    "Sari Tagh 8th street",
    "Sari Tagh 9th lane",
    "Sari Tagh 9th street",
    "Sasuntsi Davit Street",
    "Sasuntsi Davit street lane",
    "Sofia street",
    "Sofia street 1st lane",
    "Suvorov street",
    "TEC-Kharberd highway",
    "Teishebaini street",
    "TETS Highway",
    "Tigran Mets avenue",
    "Tigran Mets Avenue 1st deadlock",
    "Tigran Mets Avenue 2nd deadlock",
    "Tigran Mets Avenue 3rd lane",
    "Titogradian street",
    "Toramanyan street",
    "Toros Toramanyan street",
    "Vardan Achemyan street",
    "Vardan Achemyan Street",
    "Vardan Achemyan street 1st Lane",
    "Vardan Achemyan street 2nd deadlock",
    "Vardan Achemyan street 2nd lane",
    "Vardan Achemyan street 3rd lane",
    "Vardashen 10-th street",
    "Vardashen 11-th street",
    "Vardashen 11th street",
    "Vardashen 12th street",
    "Vardashen 1st street",
    "Vardashen 3rd street",
    "Vardashen 4th street",
    "Vardashen 5/1-th street",
    "Vardashen 5th street",
    "Vardashen 6-th street",
    "Vardashen 6th street",
    "Vardashen 7th street",
    "Vardashen 8th street",
    "Vardashen 9-th street",
    "Vardashen 9th street",
    "Vormnadirneri 2nd backstreet",
    "Vormnadirneri street",
    "Կորեացու փողոցի 1-ին փակուղի",
    "Կորեացու փողոցի 4-րդ նրբ.",
    "Կրիստալգլասս նեղային",
    "Մովսես Խորենացու փողոց",
    "Սարի Թաղ 1-ին և 2-րդ շարքեր",
    "Վարդաշենի 10-րդ փողոց",
  ],

  kanakerZeytun: [
    "Aghasi Street",
    "Aghasi Street 1st lane",
    "Aram Cholakyan street",
    "Armen Tigranyan backstreet",
    "Armen Tigranyan lane",
    "Armen Tigranyan street",
    "Avetis Aharonyan street",
    "Avetis Aharonyan Street",
    "Azatutyan Avenue",
    "Azatutyan Avenue lane",
    "Babayan street",
    "Busabanakan street",
    "David Anhaght street",
    "Davit Anhaght street",
    "Davit Anhaght Street",
    "Dro street",
    "Dro Street",
    "Dro street 1st lane",
    "Dro street 4th lane",
    "Ezras Hasratian street",
    "Ezras Hasratian Street",
    "Fanarjian 2nd pass",
    "Fanarjian street",
    "Fanarjian Street",
    "Fanarjian street 1st deadlock",
    "Fanarjyan street 1st lane",
    "Fanarjyan street 2nd lane",
    "Gercen street",
    "Gogol street",
    "Gogol street lane",
    "Hrachya Nersisyan street",
    "Hrachya Nersisyan Street",
    "Kamarak street",
    "Kamarak street 1st lane",
    "Kamaraki street 2nd lane",
    "Kanaker 16th street",
    "Kanaker 8th street",
    "Karapet Ulnetsi street",
    "Karapet Ulnetsi Street",
    "Karapet Ulnetsi street 1st deadlock",
    "Karapet Ulnetsi street 2nd deadlock",
    "Karapet Ulnetsi street 3rd deadlock",
    "Knyaz street",
    "Lambada bridge",
    "Lepsius 1-st street",
    "Lepsius 1st street",
    "Lepsius 3rd street",
    "Lepsius street",
    "Meliq Meliqyan street",
    "Meliq Meliqyan street lane",
    "Mihai Eminescu 1st street",
    "Mihai Eminescu street",
    "Minas Avetisyan 1st street",
    "Minas Avetisyan 2nd street",
    "Minas Avetisyan 3rd street",
    "Minas Avetisyan 4th street",
    "Minas Avetisyan 4th Street",
    "Minas Avetisyan street",
    "Mkrtich Sargsyan Street",
    "Nazaret Surenyan street",
    "Nersisyan deadlock",
    "Norashkharayin street",
    "Norashkharyan street",
    "Paruyr Sevak street",
    "Paruyr Sevak Street",
    "Qanaker 10th street",
    "Qanaker 11th street",
    "Qanaker 11th street 1st lane",
    "Qanaker 12th street 1st lane",
    "Qanaker 13th street",
    "Qanaker 15th street",
    "Qanaker 17th street",
    "Qanaker 6th street 1st lane",
    "Qanaqer 11th street 1st lane",
    "Qanaqer 12th street",
    "Qanaqer 1st street",
    "Qanaqer 1st street 1st lane",
    "Qanaqer 2nd street",
    "Qanaqer 2nd Street",
    "Qanaqer 2nd Street 2nd lane",
    "Qanaqer 3rd street",
    "Qanaqer 5th street",
    "Qanaqer 5th street 2nd lane",
    "Qanaqer 6th street",
    "Qanaqer 6th Street 2nd lane",
    "Qanaqer 6th Street 2th lane",
    "Qanaqer 6th Street 3rd lane",
    "Qanaqer 6th street 4th lane",
    "Qanaqer 6th Street 4th lane",
    "Qanaqer 6th Street 5th backstreet",
    "Qanaqer 6th Street 5th lane",
    "Qanaqer 9th street",
    "Raynis street",
    "Rubiniants street",
    "Rubiniants Street",
    "Rubiniants street lane",
    "Shovroyan street",
    "Tbilisian Highway",
    "Tbilisian Highway lane",
    "Tsarav Aghbyur street",
    "Ulnetsi - Rubinyants highway",
    "Usub Bek Temuryan street",
    "Vahe Vahyan street",
    "Vahe Vahyan Street",
    "Varshavyan street",
    "Vrtanes Papazyan street",
    "Yaghubyan street",
    "Zakaria Sarkavag Street",
    "Zakaria Sarkavag street 1st deadlock",
    "Zakaria Sarkavag street 1st lane",
    "Zakaria Sarkavag street 2nd lane",
    "Zakaria Sarkavag street 3rd deadlock",
    "Zakaria Sarkavag street 3rd lane",
    "Zakaria Sarkavag street 4th lane",
    "Zakaria Sarkavag street 5th lane",
    "Zakaria Sarkavag street 6th lane",
    "улица Карапета Улнеци",
    "Շրջանցիկ թունել, Կորեայի ձոր",
  ],

  ajapnyak: [
    "Abelian street",
    "Alikhanyan Brothers street",
    "Ara Ler street",
    "Ara Sargsyan street",
    "Arabkir street",
    "Arakelian street",
    "Araks street",
    "Ararat street",
    "Arpa street",
    "Arzoumanian Street",
    "Bashinjaghyan street",
    "Bashinjaghyan street 1st lane",
    "Bashinjaghyan street 2nd lane",
    "Bashinjaghyan street deadlock",
    "Bazum Street",
    "Beknazaryan street",
    "Chukhajian street",
    "Debed street",
    "Estonakan street",
    "Fuchik street",
    "Fuchik street 1st lane",
    "Fuchik street 2nd lane",
    "Gandzasar street",
    "Gevorg Chaush square",
    "Ghevond Alishan street",
    "Grigor Hasratyan street",
    "Grigor Hasratyan street lane",
    "Grigor Zohrab street",
    "Haghtanak 1st street",
    "Hakobiants street",
    "Halabyan street",
    "Halabyan Street",
    "Hasmik street",
    "Hatis street",
    "Hovhannes Erznkatsi street",
    "Hovhannes Shiraz street",
    "Hrazdan Riverbank Road",
    "Hrazdan street",
    "Huysi Avan District 1st street",
    "Janibekyan Street",
    "Karapetyan street",
    "Khoren Khachatryan street",
    "Khoren Khachatryan street 1st lane",
    "Khoren Khachatryan street 2nd lane",
    "Kievyan bridge",
    "Kirk Kerkorian street",
    "Levonyan street",
    "Lukashin 1st street",
    "Lukashin 2nd street",
    "Lukashin 3rd street",
    "Lukashin street",
    "Margarian street",
    "Margarian street 1st lane",
    "Margarian street 2nd lane",
    "Margaryan backstreet",
    "Martirosyan street",
    "Mazmanian street",
    "Meghri street",
    "Melkumov srteet",
    "Melkumov street",
    "Merdzavan highway",
    "Metaksia Simonyan street",
    "Metsarents street",
    "Mikael Mkrtchyan street",
    "Mirakyan street",
    "Miraqian deadstreet",
    "Monte Melkonian avenue",
    "Nazarbekyan block",
    "Nemrut street",
    "Nerses Shnorhali street",
    "Nikita Simonyan street",
    "Paris Herouni street",
    "Parseghov street",
    "Paruir Sevak street",
    "road to Norway District",
    "Romanos Meliqyan street",
    "Ruben Sevak street",
    "Ruben Zardaryan street",
    "Rustamyan street",
    "Sahak Partev street",
    "Sasunik Highway",
    "Sebastia street",
    "Sebastia Street",
    "Shahumyan 18th street",
    "Shinararneri street",
    "Siamanto street",
    "Silikyan 11th street",
    "Silikyan 12th street",
    "Silikyan 13th street",
    "Silikyan 1st street",
    "Silikyan 2nd street",
    "Silikyan 3rd street",
    "Silikyan 4th street",
    "Silikyan 4th street 1st lane",
    "Silikyan 5th street",
    "Silikyan 6th street",
    "Silikyan 7th street",
    "Silikyan 8th street",
    "Silikyan 9th street",
    "Silikyan new highway",
    "Silikyan old highway",
    "Sipan street",
    "Sisakyan street",
    "Sport street",
    "Terlemezyan street",
    "Tichina street",
    "Tichina street 3rd lane",
    "Tsitsernakaberd Highway",
    "Ureninery street",
    "Vahan Teryan Street",
    "Varduhi Varderesyan street",
    "Vedi street",
    "Vorotan street",
    "Vshtuni street",
    "Vshtuni street 1st lane",
    "Vshtuni street 2nd lane",
    "Vshtuni street 3rd lane",
    "Vshtuni street 4th Lane",
    "Vshtuni street 5th lane",
    "Yeghiazaryan street",
    "Հովհաննես Շիրազի փողոց",
    "Վահագնի թաղամաս",
  ],

  malatiaSebastia: [
    "Armin Vegner street",
    "Armin Vegner street 2nd lane",
    "Arno Babajanian street",
    "Artashes Kalantaryan street",
    "Baghramyan street",
    "Bagratunyats Avenue",
    "Batikyan street",
    "Charagaytain street",
    "Daniel Varujan street",
    "Deghoyan street",
    "Duryan street",
    "Gagarin street",
    "Getapnya street",
    "Gosh street",
    "Gosh street 1st deadlock",
    "Gosh street 2nd deadlock",
    "Grigor Zohrab street",
    "Gusan Sheram street",
    "Haghtanak 10th street",
    "Haghtanak 11th street",
    "Haghtanak 12th street",
    "Haghtanak 12th street 1st lane",
    "Haghtanak 13th Street",
    "Haghtanak 14th street",
    "Haghtanak 16th street",
    "Haghtanak 18-th street 3rd lane",
    "Haghtanak 18th street",
    "Haghtanak 18th street 1st lane",
    "Haghtanak 18th street 2nd lane",
    "Haghtanak 18th street 4th lane",
    "Haghtanak 1st street",
    "Haghtanak 1st street 10th lane",
    "Haghtanak 1st street 11th lane",
    "Haghtanak 1st street 1st lane",
    "Haghtanak 1st street 2nd lane",
    "Haghtanak 1st street 3rd lane",
    "Haghtanak 1st street 9th lane",
    "Haghtanak 2nd street",
    "Haghtanak 3rd street",
    "Haghtanak 3rd street 1st lane",
    "Haghtanak 3rd street 2nd lane",
    "Haghtanak 3rd street 3rd lane",
    "Haghtanak 3rd street 4th lane",
    "Haghtanak 3rd street 5th lane",
    "Haghtanak 4th street",
    "Haghtanak 5th street",
    "Haghtanak 5th street 2nd lane",
    "Haghtanak 6th street",
    "Haghtanak 7th street",
    "Haghtanak 8th street",
    "Haghtanak 9th street",
    "Hovnatan street",
    "Impasse Metsarents street",
    "Isahak Gasparyan street",
    "Israel Ori street",
    "Jambul street",
    "Jivani street",
    "Jivani street 1st deadlock",
    "Jivani street 2nd deadlock",
    "Kentronakan 1st street",
    "Kentronakan street",
    "Kurghinyan lane",
    "Kurghinyan street",
    "Leva Katvalyan street",
    "Lukashin street",
    "Malatia street",
    "Mamikonyan street",
    "Manukyan street",
    "Martikyan street",
    "Martikyan street lane",
    "Matikyan street",
    "Merdzavan highway",
    "Metsarents street",
    "Metsarents street 1st lane",
    "Mikayelyan street",
    "Mirakyan street",
    "Monte Melkonian avenue",
    "Mush District",
    "Norik Khachatryan street",
    "Noy thaghamas",
    "Ohanov street",
    "Quchak street",
    "Raffi Street",
    "Romanos Meliqyan street",
    "Saralanj street",
    "Sebastia street",
    "Sebastia Street",
    "Shahumyan 14th street",
    "Shahumyan 14th street 1st backstreet",
    "Shahumyan 14th street 1st lane",
    "Shahumyan 14th street deadlock",
    "Shahumyan 16th street",
    "Shahumyan 17th street",
    "Shahumyan 17th street 1st lane",
    "Shahumyan 18th street",
    "Shahumyan 1st street",
    "Shahumyan 1st street 1st lane",
    "Shahumyan 2nd street",
    "Shahumyan 3rd street",
    "Shahumyan 4th street",
    "Shahumyan 4th street 1st lane",
    "Shahumyan 4th street 2nd lane",
    "Shahumyan 4th street 3rd lane",
    "Shahumyan 5th street",
    "Shahumyan 6th street",
    "Shahumyan 6th street 1st deadlock",
    "Shahumyan 6th street 2nd deadlock",
    "Shahumyan 7th street",
    "Shahumyan 7th street 1st lane",
    "Sheram-Parakar highway",
    "Shrjanain street",
    "Svachyan street",
    "Tichina street",
    "Tichina street 1st deadlock",
    "Tichina street 1st lane",
    "Tichina street 2nd lane",
    "Tichina street 3rd lane",
    "Tichina street 4th lane",
    "Tichina Street 4th Lane",
    "Tserents street",
    "Tserents street 1st lane",
    "Tserents street 2nd lane",
    "Tserents street 4th lane",
    "Vakhtang Ananyan street",
    "Vantyan street",
    "Vardanyan street",
    "Voskanyan street",
    "Yaghubyan street",
    "Yervand Otyan street",
    "Zoravar Andranik street",
    "Գուսան Շերամի փողոց",
    "Րաֆֆու փողոց",
  ],

  norNork: [
    "Aksel Bakunts street",
    "Aksel Bakunts street 1st lane",
    "Aksel Bakunts street 2nd lane",
    "Artem Mikoyan street",
    "Ashot Hovhannisyan street",
    "Badal Muradyan street",
    "Baghyan street",
    "Baghyan street 1st lane",
    "Baghyan street 2nd lane",
    "Bagrevand 17th street",
    "Bagrevand 18th street",
    "Bagrevand 20th street",
    "Bagrevand 21th street",
    "Bagrevand 40th street",
    "Bagrevand 41st street",
    "Bagrevand 41st street 1st lane",
    "Bagrevand 49th street",
    "Bagrevand 50th street",
    "Bagrevand street",
    "Borian street",
    "Buzhashkhatokhneri street",
    "Davit Bek street",
    "Gai avenue",
    "Gyurjyan street",
    "Hayk Gyulikevkhyan street",
    "Hayk Gyulikevkhyan street lane",
    "Hovhannisyan street",
    "Hunan Avetisyan street",
    "Ivan Tevosyan street",
    "Jrvezh 3rd street",
    "Jrvezh 5th street",
    "Jrvezh 6th street",
    "Jughayi street",
    "Karakhanyan street",
    "Kocharyan street",
    "Luxemburg street",
    "Luxemburg street 1st lane",
    "Luxemburg street 2nd lane",
    "Lvovyan street",
    "Lvovyan street deadlock",
    "Malyan lane",
    "Marr street",
    "Marr street lane",
    "Mayak district",
    "Melqonyan street",
    "Minsk street",
    "Moldovakan street",
    "Mushegh Galshoyan street",
    "Nansen street",
    "Nansen street lane",
    "Nelson Stepanyan street",
    "Nork 2nd street",
    "Nork pass",
    "Old & New Norks passing",
    "Pavel Safyan lane",
    "Razmik street",
    "Samvel Safaryan street",
    "Shopron street",
    "Shopron street 1st lane",
    "Shopron street 2nd lane",
    "Shopron street 3rd lane",
    "Shopron street 4th lane",
    "Tatul Javrushyan street",
    "Vahan Totovents street",
    "Vahan Totovents street lane",
    "Vakhtangov street",
    "Vilnyus street",
    "Այգեգործների փողոց",
    "Ռազմիկի փ.",
    "Սիրող Սրտեր Թաղամաս",
  ],

  norkMarash: [
    "Ara Harutyunyan street",
    "Ara Harutyunyan street 1st lane",
    "Ara Harutyunyan street 2nd lane",
    "Armenak Armenakyan Street",
    "Armenakyan 1st street pass",
    "Arpenik Nalbandyan street",
    "Aygestan 11th street deadlock",
    "Aytsemnik Urartu street",
    "Buzhashkhatokhner street",
    "Buzhashkhatokhneri street",
    "Charents street 1st lane",
    "Davit Bek street",
    "Eduard Isabekyan street",
    "Garegin Hovsepyan Street",
    "Gevorg Jahukyan street",
    "Lusine Zakaryan street",
    "Nork 15th street",
    "Nork 17th street 1st lane",
    "Nork 2nd street",
    "Nork 3rd street",
    "Nork 5th street",
    "Nork 7th street 1st lane",
    "Norqi Ayginer street",
    "Ohan Duryan street",
    "Old & New Norks passing",
    "Sargis Baghdasaryan street",
    "Sari Tagh 5th and 6th lines",
    "Sari Tagh 8th and 9th lines",
    "Sero Khanzadyan street",
    "Sero Khanzadyan Street",
    "Sero Khanzadyan street 1st lane",
    "Sero Khanzadyan street 2nd lane",
    "Suren Safaryan street",
    "Tereza Mirzoyan street",
    "Yerem Vardanyan street",
    "Արմենակ Արմենակյան նրբանցք",
    "Նորքի 10-րդ փողոց",
    "Նորքի 15-րդ փողոց",
  ],

  nubarashen: [
    "Artashat-Sevan highway",
    "B-1 microdistrict",
    "B-10 microdistrict",
    "B-2 microdistrict",
    "B-3 microdistrict",
    "B-4 microdistrict",
    "B-5 microdistrict",
    "B-6 microdistrict",
    "B-8 microdistrict",
    "B-9 microdistrict",
    "Bardzrashen-Nubarashen highway",
    "Chnkushi street",
    "Jrashen Highway",
    "Lanjazat-Nubarashen highway",
    "Nor Zmyurnia street",
    "Nubarashen 10th street",
    "Nubarashen 11th street",
    "Nubarashen 12th street",
    "Nubarashen 15th Street",
    "Nubarashen 16th street",
    "Nubarashen 17th street",
    "Nubarashen 18th street",
    "Nubarashen 1st street",
    "Nubarashen 20th street",
    "Nubarashen 2nd street",
    "Nubarashen 3rd street",
    "Nubarashen 4th street",
    "Nubarashen 5th street",
    "Nubarashen 6th street",
    "Nubarashen 7th street",
    "Nubarashen 8th street",
    "Nubarashen 9th street",
    "Nubarashen highway",
    "TEC-Kharberd highway",
  ],

  shengavit: [
    "10th street Kharberd",
    "11th street Kharberd",
    "12th street Kharberd",
    "13th street Kharberd",
    "14th street Kharberd",
    "15th street Kharberd",
    "16th street Kharberd",
    "17th street Kharberd",
    "18th street Kharberd",
    "19th street Kharberd",
    "1st line",
    "1st street",
    "1st street Kharberd",
    "20th street Kharberd",
    "21st street Kharberd",
    "22nd street Kharberd",
    "23rd street Kharberd",
    "24th street Kharberd",
    "25th street Kharberd",
    "26th street Kharberd",
    "27th street Kharberd",
    "28th street Kharberd",
    "2nd street Kharberd",
    "3rd street Kharberd",
    "4th street Kharberd",
    "5th street Kharberd",
    "6th street Kharberd",
    "7th street Kharberd",
    "8th street Kharberd",
    "9th street",
    "9th street Kharberd",
    "Ajapnyak street Kharberd",
    "Amerikyan street",
    "Antarayin street Kharberd",
    "Aragats street",
    "Araratyan street",
    "Araratyan street 1st lane",
    "Araratyan street 2nd lane",
    "Arin Berd street",
    "Arin Berd street 1st lane",
    "Arin Berd street 2nd lane",
    "Armen Khostikyan",
    "Armen Khostikyan street",
    "Arshakuniats Avenue",
    "Arshakuniats avenue 3rd lane",
    "Arshakuniats avenue 4th lane",
    "Artashat highway",
    "Artashat highway 1st lane",
    "Artashisyan street",
    "Artashisyan street 1st lane",
    "Artashisyan street 2nd lane",
    "Artashisyan street 3rd lane",
    "Artsakh avenue",
    "Artsakh avenue 4th lane",
    "Bagratunyats Avenue",
    "Bagratunyats Avenue 1st lane",
    "Bagratunyats Avenue 2nd lane",
    "Bagratunyats Avenue 3rd backstreet",
    "Bagratunyats Avenue 4th lane",
    "Baydukov street",
    "Benik Petrosyan street",
    "Boris Piotrovsky street",
    "Chekhov street",
    "Chekhov street 1st lane",
    "Dodokhyan street",
    "Dzor street Kharberd",
    "Eghishe Tadevosyan backstreet",
    "Elvina Makaryan street",
    "Evgeny Bayburdyan street",
    "Frunze Dovlatyan street",
    "Frunze street",
    "Garegin Nzhdeh square",
    "Garegin Nzhdeh Street",
    "Gharibjanyan street",
    "Gorgagotsneri street",
    "Hayk Hovsepyan street",
    "Hayk Hovsepyan Street",
    "Hovhannes Grigoryan street",
    "Hovhannes Hovhannisyan Street",
    "Hrant Vardanyan street",
    "Hrazdan street",
    "Kara-Murza street",
    "Karmir Blur street",
    "Kashegortsner street",
    "Kentronakan street Kharberd",
    "Koghb 1st street",
    "Koryun Hakobyan street",
    "Kotovsky street",
    "Kristapor street",
    "Labour Square",
    "Lazo lane",
    "Lazo street",
    "Levon Hayrapetyan street",
    "Levon Khachikyan street",
    "Madoyan street",
    "Manandyan street",
    "Mantashyan street",
    "Mantashyan street lane",
    "Markvart street",
    "Masis street",
    "Masis street 3rd lane",
    "Masis-Yerevan Highway",
    "Mayis 9 street",
    "Mikayel Nalbandyan street Kharberd",
    "Mkhchyan street",
    "Mkrtich Sedrakyan street",
    "Musaelyan street",
    "Nairit-Noragavit highway",
    "Nerkin Charbakh 10th street",
    "Nerkin Charbakh 10th street 1st backstreet",
    "Nerkin Charbakh 11th street",
    "Nerkin Charbakh 12th street",
    "Nerkin Charbakh 12th street 1st lane",
    "Nerkin Charbakh 12th street 2nd lane",
    "Nerkin Charbakh 12th street 3nd lane",
    "Nerkin Charbakh 12th street 4nd lane",
    "Nerkin Charbakh 13th street",
    "Nerkin Charbakh 14th street",
    "Nerkin Charbakh 15th street",
    "Nerkin Charbakh 1st street",
    "Nerkin Charbakh 2nd street",
    "Nerkin Charbakh 3rd street",
    "Nerkin Charbakh 3rd street 1st lane",
    "Nerkin Charbakh 3rd street 2nd lane",
    "Nerkin Charbakh 3rd street 3rd lane",
    "Nerkin Charbakh 4th street",
    "Nerkin Charbakh 5th street",
    "Nerkin Charbakh 5th street 2nd lane",
    "Nerkin Charbakh 5th street 3nd lane",
    "Nerkin Charbakh 5th street lane",
    "Nerkin Charbakh 6th street",
    "Nerkin Charbakh 7th street",
    "Nerkin Charbakh 7th street 7th backstreet",
    "Nerkin Charbakh 8th street",
    "Nerkin Charbakh 8th street lane",
    "Nerkin Charbakh 9th street",
    "Nerqin Shengavit 11th street",
    "Nerqin Shengavit 11th street 1st deadlock",
    "Nerqin Shengavit 11th street 2nd deadlock",
    "Nerqin Shengavit 12th street deadlock",
    "Nerqin Shengavit 13th street",
    "Nerqin Shengavit 14th street",
    "Nerqin Shengavit 14th street 1st deadlock",
    "Nerqin Shengavit 14th street 2nd lane",
    "Nerqin Shengavit 15th street",
    "Nerqin Shengavit 15th street 1st lane",
    "Nerqin Shengavit 9th street",
    "Nikoghayos Buniatyan street",
    "Nizami street",
    "Noragavit 10th backstreet",
    "Noragavit 10th street",
    "Noragavit 11th street",
    "Noragavit 11th street lane",
    "Noragavit 12th street",
    "Noragavit 12th street lane",
    "Noragavit 13th street",
    "Noragavit 13th street lane",
    "Noragavit 14th street",
    "Noragavit 1st street",
    "Noragavit 1st street 1st deadlock",
    "Noragavit 1st street 2nd deadlock",
    "Noragavit 1st street 3rd deadlock",
    "Noragavit 1st street 4th deadlock",
    "Noragavit 1st street 5th deadlock",
    "Noragavit 2nd street",
    "Noragavit 2nd street lane",
    "Noragavit 3rd street",
    "Noragavit 3rd street lane",
    "Noragavit 4th street",
    "Noragavit 4th street lane",
    "Noragavit 5th street",
    "Noragavit 6th street",
    "Noragavit 6th street 2nd deadlock",
    "Noragavit 6th street 3rd deadlock",
    "Noragavit 7th street",
    "Noragavit 7th street lane",
    "Noragavit 8th street",
    "Noragavit 9th street",
    "Noragavit 9th street lane",
    "Norayr Karganyan street",
    "Odessa street",
    "Patkanyan street",
    "Popov street",
    "S. Sargsyan street",
    "Sedrak Sagsyan street",
    "Sevan street",
    "Sevan street 1st deadlock",
    "Sevan street 2nd deadlock",
    "Sevan street lane",
    "Shahamiryanner street",
    "Sharuri street",
    "Sharuri Street",
    "Sharuri street lane",
    "Shengavit 9th street",
    "Shengavit street",
    "Shevchenko street",
    "Shirak Mush street",
    "Shirak street",
    "Shirak street 2nd deadlock",
    "Shirak street 2nd lane",
    "Shirak street 3rd lane",
    "Shirak street 4th lane",
    "Shirak street 5th lane",
    "Smbat Zoravar street",
    "Tamantsiner street",
    "Tamantsiner street 6th lane",
    "Taronts backstreet",
    "Taronts street",
    "Taronts street 1st Lane",
    "Taronts street 3rd lane",
    "Tatik Saryan street",
    "TEC-Kharberd highway",
    "Teishebaini street",
    "Timiryazev street",
    "Timiryazev street deadlock",
    "Verin Shengavit 10th street",
    "Verin Shengavit 11th street",
    "Verin Shengavit 1st street",
    "Verin Shengavit 2nd street",
    "Verin Shengavit 2nd street 1st deadlock",
    "Verin Shengavit 2nd street 2nd deadlock",
    "Yeghbayrutyan street",
    "Yeghbayrutyan street 1st lane",
    "Yeghishe Tadevosyan Street",
    "Z. Yesayan street",
    "Կողբի 1-ին փողոց",
    "Կողբի 2-րդ փողոց",
    "Հրազդան փողոց",
  ],

  other: [
  ],

};

export const allKnownStreets: Set<string> = new Set(
  Object.values(streetsByDistrict).flat()
);

export function isStreetInDistrict(district: string, street: string): boolean {
  if (!street || !street.trim()) return true;
  const list = streetsByDistrict[district];
  if (!list || list.length === 0) return true;
  const norm = (s: string) => s.trim().toLowerCase();
  return list.some((s) => norm(s) === norm(street));
}